// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egrclphncuxtiwgypald.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncmNscGhuY3V4dGl3Z3lwYWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDU3NzUsImV4cCI6MjA2MTY4MTc3NX0.jgWOqAuRm6Ngk8fXsZcjA-6wvh4aNBLuGTou_3ar4kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);